# Load RC
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

[ -s $HOME/.nvm/nvm.sh ] && . $HOME/.nvm/nvm.sh # This loads NVM
if [ -e /Users/kenhkan/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/kenhkan/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
