" Compatibility hacks
set shell=/bin/bash
set nocompatible

" Default color scheme
let &background="light"

" NeoBunlde stuff
if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#rc(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
NeoBundleFetch 'Shougo/neobundle.vim'

" NeoBundles
NeoBundle 'Shougo/vimproc'
NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'kchmck/vim-coffee-script'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'scrooloose/nerdcommenter'
NeoBundle 'digitaltoad/vim-jade'

" Required for NeoBundle
filetype plugin indent on

" NeoBundle installation check.
NeoBundleCheck

" Highlighting
syntax enable
set number
set ruler

" Use relative line numbering
set nonumber
set relativenumber
set rnu

" Indentation
set smartindent
set autoindent

" No hard wrap
set wrap
set tw=0
set fo=cq
set wm=0

" Use spaces, not tabs
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=2

" Font & Style
set guifont=Consolas:h14
set antialias

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

" Backspace
set backspace=indent,eol,start

" Status bar
set laststatus=2

" Use ; instead of : to save the shift keystroke
noremap ; :

" Use ? to repeat last command
noremap ? .

" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" Normally Y copies the whole row - not from cursor to EOL like other capitals. Make Y behave like other capitals
map Y y$

" Show tab guides
set lcs=tab:\⁞\
set list listchars=tab:\ \ ,trail:·

" Clean trailing space
nnoremap <Leader>c :%s/<Space>\+$//<CR>

" Use sane (i.e. normal) regexes
noremap / /\v

" Split screen
nmap * <C-w>v
nmap # <C-w>s

" Arrow keys move among splits in normal mode
nmap <Left> <C-W>h
nmap <Right> <C-W>l
nmap <Up> <C-W>k
nmap <Down> <C-W>j

" Arrow keys for indentation in visual mode
vmap <Left> <gv
vmap <Right> >gv

" Commenting
vmap ] <Leader>clgv
vmap [ <Leader>cugv

" Max out the height of the current split
nmap <Leader>h <C-W>_
" Max out the width of the current split
nmap <Leader>g <C-W>\|
" Normalize all split sizes, which is very handy when resizing terminal
nmap <Leader>n <C-W>=
" Swap top/bottom or left/right split
nmap <Leader>s <C-W>R

" Shortcuts for scrolling
nmap K <C-u>
nmap J <C-d>

" Cut/Copy to clipboard
vnoremap c "+y
vnoremap C "+d
nnoremap c "+p
nnoremap C "+P

" Search by file/buffer name
nnoremap ' :Unite<Space>file_rec/async<Space>buffer<CR>
" Search directory content
nnoremap : :Unite<Space>grep:.<CR>
" Select buffer
nnoremap . :Unite<Space>-quick-match<Space>buffer<CR>
" Enable yank history
let g:unite_source_history_yank_enable = 1

" NERDTree
nnoremap , :NERDTreeToggle<ENTER>
" Close NERDTree on file opened
let NERDTreeQuitOnOpen = 1
