#!/usr/bin/env bash

>&2 echo "----> Installing Xcode..."
xcode-select --install
>&2 echo "----> Please restart after Xcode has been installed."

cd ~/Desktop
git clone https://github.com/kenhkan/config.git
cd config
git pull origin master
bin/setup
