#!/usr/bin/env bash

if [[ ! -d /Applications/Xcode.app ]]; then
  >&2 echo "----> Installing Xcode..."
  xcode-select --install
  >&2 echo "----> Please restart after Xcode has been installed."
  exit 3
fi

cd ~/Desktop
git clone https://github.com/kenhkan/config.git
cd config
git pull origin master
bin/setup
