- hosts: localhost
  vars:
    home: /Users/kenhkan

    shortcuts:
      - { from: "v", to: "/Volumes" }
      - { from: "d", to: "{{ home }}/Desktop" }
      - { from: "c", to: "{{ home }}/Desktop/code" }
      - { from: "h", to: "{{ home }}/Desktop/code/hack" }
      - { from: "w", to: "{{ home }}/Downloads" }

    programs:
      - ag
      - vim
      - git
      - haskell-stack
      - antlr
      - heroku-toolbelt
      - parallel
      - rust
      - caskroom/cask/brew-cask
      - ghc
      - node
      - git-lfs
      - osquery
      - p7zip

    applications:
      - "0xed"
      - google-chrome
      - fish
      - iterm2
      - skitch
      - spectacle
      - torbrowser
      - virtualbox
      - backblaze
      - firefox
      - java
      - textmate
      - tuxera-ntfs
      - vagrant
      - vlc
      - diffmerge
      - knockknock
      - blockblock
      - archiver
      - elm-platform

  tasks:
    - name: Install programs with homebrew
      homebrew: name={{ item }} state=present update_homebrew=yes
      with_items: programs

    - name: Create top-level directories
      file: path={{ home }}/Desktop/{{ item }} state=directory
      with_items:
        - code
        - code/hack

    - name: Create shortcut directory
      file: path={{ home }}/s state=directory

    - name: Clone config
      git: repo=https://github.com/kenhkan/config.git dest={{ home }}/Desktop/code/config update=no accept_hostkey=yes

    - name: Symlink config
      file: path={{ home }}/.config src={{ home }}/Desktop/code/config state=link

    - name: Symlink dotfiles in config
      file: path={{ home }}/.{{ item }} src={{ home }}/Desktop/code/config/dotfiles/{{ item }} state=link
      with_items:
        - ackrc
        - editorconfig
        - gitconfig
        - gitignore
        - vimrc

    - name: Symlink stack config
      file: path={{ home }}/.stack/config.yaml src={{ home }}/Desktop/code/config/dotfiles/stack state=link

    - name: Setup shortcuts
      file: path={{ home }}/s/{{ item.from }} src={{ item.to }} state=link
      with_items: shortcuts

    - name: Include old versions of casks
      shell: brew tap caskroom/versions

    - name: Check for installed applications
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true

    - name: Install applications with brew cask
      shell: brew cask install {{ item }}
      with_items: applications
      when: item not in installed_applications.results | map(attribute='stdout')

    - name: Copy fonts
      copy: dest={{ home }}/Library/Fonts/ src=../fonts/Input

    - name: Set startup items
      shell: osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Users/kenhkan/Applications/{{ item }}.app", hidden:false}'
      with_items:
        - Spectacle
        - "Google Chrome"

    - name: Copy over plists
      copy: dest={{ home }}/Library/Preferences/ src=../plists/{{ item }}
      with_items:
        - com.apple.finder.plist
        - com.apple.dock.plist
        - com.apple.symbolichotkeys.plist
        - com.googlecode.iterm2.plist
