- hosts: localhost
  vars:
    home: /Users/kenhkan
    program:
      - git
      - haskell-stack
      - antlr
      - heroku-toolbelt
      - parallel
      - rust
      - caskroom/cask/brew-cask
      - ghc
      - node
    applications:
      - "0xed"
      - google-chrome
      - fish
      - iterm2
      - keka
      - skitch
      - spectacle
      - torbrowser
      - unrarx
      - virtualbox
      - backblaze
      - firefox
      - java
      - textmate
      - tuxera-ntfs
      - vagrant
      - vlc

  tasks:
    - name: Install programs with homebrew
      homebrew: name={{ item }} state=present update_homebrew=yes
      with_items: programs

    - name: Create code directory
      file: path={{ home }}/Desktop/code state=directory

    - name: Clone configurations
      git: repo=https://github.com/kenhkan/config.git dest={{ home }}/Desktop/code/config update=no accept_hostkey=yes

    - name: Symlink dotfiles
      file: path={{ home }}/.{{ item }} src={{ home }}/Desktop/code/config/dotfiles/{{ item }} state=link
      with_items:
        - ackrc
        - editorconfig
        - gitconfig
        - gitignore
        - vimrc

    - name: Symlink neovim config
      file: path={{ home }}/.nvimrc src={{ home }}/.vimrc state=link

    - name: Check for installed apps
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true

    - name: Install apps with brew-cask
      shell: brew cask install {{ item }}
      with_items: applications
      when: item not in installed_applications.results | map(attribute='stdout')
