- hosts: localhost
  vars:
    home: /Users/kenhkan
    programs:
      - vim
      - git
      - haskell-stack
      - antlr
      - heroku-toolbelt
      - parallel
      - rust
      - caskroom/cask/brew-cask
      - ghc
      - node
    applications:
      - "0xed"
      - google-chrome
      - fish
      - iterm2
      - keka
      - skitch
      - spectacle
      - torbrowser
      - unrarx
      - virtualbox
      - backblaze
      - firefox
      - java
      - textmate
      - tuxera-ntfs
      - vagrant
      - vlc

  tasks:
    - name: Install programs with homebrew
      homebrew: name={{ item }} state=present update_homebrew=yes
      with_items: programs

    - name: Create code directory
      file: path={{ home }}/Desktop/code state=directory

    - name: Clone config
      git: repo=https://github.com/kenhkan/config.git dest={{ home }}/Desktop/code/config update=no accept_hostkey=yes

    - name: Symlink into config
      file: path={{ home }}/.{{ item }} src={{ home }}/Desktop/code/config/{{ item }} state=link
      with_items:
        - .
        - dotfiles/ackrc
        - dotfiles/editorconfig
        - dotfiles/gitconfig
        - dotfiles/gitignore
        - dotfiles/vimrc

    - name: Check for installed applications
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true

    - name: Install applications with brew cask
      shell: brew cask install {{ item }}
      with_items: applications
      when: item not in installed_applications.results | map(attribute='stdout')
