- hosts: localhost

  vars:
    home: "{{ ansible_env.HOME }}"

    shortcuts:
      - { from: "v", to: "/Volumes" }
      - { from: "d", to: "{{ home }}/Desktop" }
      - { from: "c", to: "{{ home }}/Desktop/code" }
      - { from: "h", to: "{{ home }}/Desktop/code/hack" }
      - { from: "w", to: "{{ home }}/Downloads" }
      - { from: "o", to: "{{ home }}/Movies" }
      - { from: "p", to: "{{ home }}/Dropbox/projects" }
      - { from: "r", to: "{{ home }}/Dropbox/print" }

    programs:
      - ag
      - vim
      - git
      - haskell-stack
      - antlr
      - heroku-toolbelt
      - parallel
      - rust
      - node
      - git-lfs
      - osquery
      - p7zip
      - ffmpeg
      - exiftool
      - coreutils
      - binutils
      - cloc
      - python
      - jq
      - postgresql
      - git-when-merged

    applications:
      - "0xed"
      - google-chrome
      - fish
      - iterm2
      - skitch
      - spectacle
      - torbrowser
      - virtualbox
      - backblaze
      - firefox
      - java
      - sublime-text3
      - tuxera-ntfs
      - vagrant
      - vlc
      - diffmerge
      - knockknock
      - blockblock
      - archiver
      - elm-platform
      - slack
      - transmission
      - dropbox
      - soundflower
      - sequel-pro

    stack_commands:
      - { user: "jaspervdj", repo: "stylish-haskell" }

  tasks:
    - name: Install programs with homebrew
      homebrew: name={{ item }} state=present update_homebrew=yes
      with_items: programs

    - name: Create top-level directories
      file: path={{ home }}/Desktop/{{ item }} state=directory
      with_items:
        - code
        - code/hack

    - name: Create shortcut directories
      file: path={{ home }}/s state=directory

    - name: Create other directories
      file: path={{ home }}/.stack state=directory

    - name: Symlink config
      file: path={{ home }}/.config src={{ home }}/Desktop/config state=link

    - name: Apply default DS_Store
      copy: src={{ home }}/Desktop/config/etc/DS_Store dest={{ home }}/.DS_Store

    - name: Symlink dotfiles in config
      file: path={{ home }}/.{{ item }} src={{ home }}/Desktop/config/dotfiles/{{ item }} state=link
      with_items:
        - ackrc
        - editorconfig
        - gitconfig
        - gitignore
        - vimrc

    - name: Symlink stack config
      file: path={{ home }}/.stack/config.yaml src={{ home }}/Desktop/config/dotfiles/stack state=link force=yes

    - name: Fetch executables that require stack
      with_items: stack_commands
      git: repo=git@github.com:{{ item.user }}/{{ item.repo }}.git dest={{ home }}/Desktop/code/hack/{{ item.repo }} update=yes

    - name: Install executables that require stack
      with_items: stack_commands
      shell: stack install chdir={{ home }}/Desktop/code/hack/{{ item.repo }}

    - name: Setup shortcuts
      file: path={{ home }}/s/{{ item.from }} src={{ item.to }} state=link
      with_items: shortcuts

    - name: Include old versions of casks
      shell: brew tap caskroom/versions

    - name: Install Cask
      shell: brew tap caskroom/cask

    - name: Check for installed applications
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true

    - name: Install applications with brew cask
      shell: brew cask install {{ item }}
      with_items: applications
      when: item not in installed_applications.results | map(attribute='stdout')

    - name: Install autoformatter
      pip: name=autopep8 state=present

    - name: Copy fonts
      copy: dest={{ home }}/Library/Fonts/ src=../fonts/Input

    - name: Set startup items
      shell: osascript -e 'tell application "System Events" to make login item at end with properties {path:"{{ home }}/Applications/{{ item }}.app", hidden:false}'
      with_items:
        - Spectacle
        - "Google Chrome"
