- hosts: localhost
  vars:
    home: /Users/kenhkan

    shortcuts:
      c:
        from: "{{ home }}/Desktop/code"
      d:
        from: "{{ home }}/Desktop"
      h:
        from: "{{ home }}/Desktop/hack"
      v:
        from: "/Volumes"
      w:
        from: "{{ home }}/Downloads"

    programs:
      - ag
      - vim
      - git
      - haskell-stack
      - antlr
      - heroku-toolbelt
      - parallel
      - rust
      - caskroom/cask/brew-cask
      - ghc
      - node

    applications:
      - "0xed"
      - google-chrome
      - fish
      - iterm2
      - keka
      - skitch
      - spectacle
      - torbrowser
      - unrarx
      - virtualbox
      - backblaze
      - firefox
      - java
      - textmate
      - tuxera-ntfs
      - vagrant
      - vlc

  tasks:
    - name: Install programs with homebrew
      homebrew: name={{ item }} state=present update_homebrew=yes
      with_items: programs

    - name: Create top-level directories
      file: path={{ home }}/Desktop/{{ item }} state=directory
      with_items:
        - code
        - hack

    - name: Clone config
      git: repo=https://github.com/kenhkan/config.git dest={{ home }}/Desktop/code/config update=no accept_hostkey=yes

    - name: Symlink config
      file: path={{ home }}/.config src={{ home }}/Desktop/code/config state=link

    - name: Symlink dotfiles in config
      file: path={{ home }}/.{{ item }} src={{ home }}/Desktop/code/config/dotfiles/{{ item }} state=link
      with_items:
        - ackrc
        - editorconfig
        - gitconfig
        - gitignore
        - vimrc

    - name: Create shortcut directory
      file: path={{ home }}/s state=directory

    - name: Setup shortcuts
      file: path={{ home }}/s/{{ item.key }} src={{ item.value.from }}
      with_dict: "{{ shortcuts }}"

    - name: Check for installed applications
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true

    - name: Install applications with brew cask
      shell: brew cask install {{ item }}
      with_items: applications
      when: item not in installed_applications.results | map(attribute='stdout')

    - name: Copy fonts
      copy: dest={{ home }}/Library/Fonts/ src=../fonts/Input

    - name: Set startup items
      shell: osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Users/kenhkan/Applications/{{ item }}.app", hidden:false}'
      with_items:
        - Spectacle
        - "Google Chrome"

    - name: Copy over plists
      copy: dest={{ home }}/Library/Preferences/ src=../plists/{{ item }}
      with_items:
        - com.apple.dock.plist
        - com.apple.symbolichotkeys.plist
