#!/usr/bin/env bash

###############################################################################
# Replace iTunes with an empty app
###############################################################################

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Replace iTunes
sudo mv /Applications/iTunes.app /Applications/iTunes.backup.app
sudo cp $DIR/../etc/DoNothing.app /Applications/iTunes.app

# Create empty group.
sudo dscl . -create /groups/nobody
sudo dscl . -append /groups/nobody gid 4200
sudo dscl . -append /groups/nobody passwd "*"

# Change ownership of empty iTunes
chown root /Applications/iTunes.app/
sudo chmod 0700 /Applications/iTunes.app/
sudo chgrp nobody /Applications/iTunes.app/
