#!/usr/bin/env bash

###############################################################################
# Set up shortcuts
###############################################################################

mkdir ~/s
cd ~/s
ln -s d /Users/kenhkan/Desktop
ln -s v /Volumes
ln -s w /Users/kenhkan/Downloads/
