#!/usr/bin/env bash

###############################################################################
# Set up shortcuts
###############################################################################

mkdir ~/s
cd ~/s
ln -s /Users/kenhkan/Desktop d 
ln -s /Volumes v 
ln -s /Users/kenhkan/Downloads w
