#!/usr/bin/env bash

###############################################################################
# Set up shortcuts
###############################################################################

mkdir -P $HOME/s
cd $HOME/s

ln -sfhF $HOME/Desktop $HOME/s/d
ln -sfhF /Volumes $HOME/s/v
ln -sfhF $HOME/Downloads $HOME/s/w
