#!/usr/bin/env bash

if [ ! -d $HOME/.ssh ]; then

  # See https://help.github.com/articles/generating-ssh-keys/
  ssh-keygen -t rsa -b 4096 -C "kenhkan@gmail.com"
  eval "$(ssh-agent -s)"
  ssh-add ~/.ssh/id_rsa

  # Password-less login locally
  # http://stackoverflow.com/questions/7439563/how-to-ssh-to-localhost-without-password
  cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  chmod og-wx ~/.ssh/authorized_keys 

fi
