#!/usr/bin/env bash

if [ ! -d $HOME/.ssh ]; then

  # See https://help.github.com/articles/generating-ssh-keys/
  ssh-keygen -t rsa -b 4096 -C "kenhkan@gmail.com"
  eval "$(ssh-agent -s)"
  ssh-add ~/.ssh/id_rsa

fi
